import Head from "next/head"
import Card from "@components/Card"
import Grid from "@components/Grid"
import classes from "./Pages.module.scss"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container align="center" justify="center">
        <span className={classes.Title}>
          Todos los comercios en un solo lugar
        </span>
      </Grid>
      <div className="GridContainer">
        {Array(10)
          .fill("")
          .map((el: any, i: any) => (
            <div key={i} style={{ paddingTop: 50 }}>
              <Card />
            </div>
          ))}
      </div>
    </div>
  )
}
