import Head from "next/head"
import { GetStaticProps } from "next"
import axios from "axios"
import { gql } from "@apollo/client"
import client from "../apollo/apollo-client"

import HomePage from "../home/screens/Home"

import { IItem } from "../home/screens/Home"

interface IHome {
  location_data: any
  initial_business: IItem[]
}

export default function Home({ location_data, initial_business }: IHome) {
  console.log(initial_business)
  return (
    <div>
      <Head>
        <title>Guru Yelp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage initialBusiness={initial_business} />
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  try {
    const url_ip = "https://ipgeolocation.abstractapi.com/v1"
    const response = await axios.get(url_ip, {
      params: {
        api_key: process.env.API_KEY_ABSTRACT
      }
    })

    const city = response.data.city.toString()
    const { data: data_business } = await client.query({
      query: gql`
        query GetDataSearch {
          search(term: "restaurantes", location: "${city}", limit: 10) {
            business {
              id
              phone
              display_phone
              review_count
              rating
              photos
              name
              location {
                address1
                city
                state
                country
              }
            }
          }
        }
      `
    })

    return {
      props: {
        location_data: response.data,
        initial_business: data_business.search.business
      },
      revalidate: 300
    }
  } catch (error) {
    return {
      props: {
        error
      }
    }
  }
}
