import Head from "next/head"
import { GetStaticProps } from "next"
import axios from "axios"

import HomePage from "../home/screens/Home"

export default function Home({ location_data }) {
  console.log(location_data)
  return (
    <div>
      <Head>
        <title>Guru Yelp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  try {
    const url_ip = "https://ipgeolocation.abstractapi.com/v1"
    const response = await axios.get(url_ip, {
      params: {
        api_key: process.env.API_KEY_ABSTRACT
      }
    })
    const latitude = response.data.latitude.toString()
    const longitude = response.data.longitude.toString()
    return {
      props: {
        location_data: response.data
      }
      // revalidate: 300
    }
  } catch (error) {
    return {
      props: {
        error
      }
    }
  }
}
